### ISSUE TITLE
dynamic node discovery

### ISSUE THREAD

**Issue by brueckenc** [s7/scale7-pelops#4]
I get this error when dynamic node discovery is enabled 

WARN [pool-1-thread-1] 2010-09-01 12:34:55,719 CachePerNodePool.java (line 283) Cluster watcher process encountered error while refreshing snapshot
org.apache.thrift.TApplicationException: describe_keyspaces failed: unknown result
    at org.apache.cassandra.thrift.Cassandra$Client.recv_describe_keyspaces(Cassandra.java:1038)
    at org.apache.cassandra.thrift.Cassandra$Client.describe_keyspaces(Cassandra.java:1009)
    at org.scale7.cassandra.pelops.KeyspaceManager$1.execute(KeyspaceManager.java:29)
    at org.scale7.cassandra.pelops.KeyspaceManager$1.execute(KeyspaceManager.java:26)
    at org.scale7.cassandra.pelops.ManagerOperand.tryOperation(ManagerOperand.java:146)
    at org.scale7.cassandra.pelops.KeyspaceManager.getKeyspaceNames(KeyspaceManager.java:32)
    at org.scale7.cassandra.pelops.Cluster.refreshNodesSnapshot(Cluster.java:62)
    at org.scale7.cassandra.pelops.CachePerNodePool$1.run(CachePerNodePool.java:274)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:637)

**Comment by danwashusen** [comment]
Is it possible that you're using different versions of the cassandra client and cassandra?  The latest snapshot versions of Pelops are tracking against the cassandra hudson build...

**Comment by brueckenc** [comment]
yes.   I believe I had a libthrift version mismatch.   The libthrift was a remant from a build before I started using pelops.

**Comment by danwashusen** [comment]
Good to hear.
