### ISSUE TITLE
NPE on loadSuperColumn

### ISSUE THREAD

**Issue by mevivs** [s7/scale7-pelops#40]
Code:

rowId and superColumnNames are present in Cassandra DB
selector.getSuperColumnsFromRow(columnFamily, rowId, Selector.newColumnsPredicate(superColumnNames),
ConsistencyLevel.ONE);

Caused by: java.lang.NullPointerException
at org.apache.thrift.protocol.TBinaryProtocol.writeBinary(TBinaryProtocol.java:194)
at org.apache.cassandra.thrift.SlicePredicate.write(SlicePredicate.java:432)
at org.apache.cassandra.thrift.Cassandra$get_slice_args.write(Cassandra.java:6591)
at org.apache.cassandra.thrift.Cassandra$Client.send_get_slice(Cassandra.java:523)
at org.apache.cassandra.thrift.Cassandra$Client.get_slice(Cassandra.java:511)

Any suggestion?

**Comment by danwashusen** [comment]
You'll need to provide a fair bit more info, but at a guess I'd say 'superColumnNames' contains a null value...

**Comment by mevivs** [comment]
Thanks.. String array was containing one SuperColumnName as Null was causing the issue.
It is working fine... But still wondering if we should throw or warn with prechecks on such null values?
