### ISSUE TITLE
getting incompatibleclasschange error

### ISSUE THREAD

**Issue by denen99** [s7/scale7-pelops#50]
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at org.scale7.cassandra.pelops.Connection.<init>(Connection.java:56)
    at org.scale7.cassandra.pelops.pool.CommonsBackedPool$PooledConnection.<init>(CommonsBackedPool.java:860)
    at org.scale7.cassandra.pelops.pool.CommonsBackedPool$ConnectionFactory.makeObject(CommonsBackedPool.java:887)
    at org.apache.commons.pool.impl.GenericKeyedObjectPool.addObject(GenericKeyedObjectPool.java:1729)
    at org.apache.commons.pool.impl.GenericKeyedObjectPool.ensureMinIdle(GenericKeyedObjectPool.java:2095)
    at org.apache.commons.pool.impl.GenericKeyedObjectPool.preparePool(GenericKeyedObjectPool.java:1766)
    at org.scale7.cassandra.pelops.pool.CommonsBackedPool.addNode(CommonsBackedPool.java:423)
    at org.scale7.cassandra.pelops.pool.CommonsBackedPool.<init>(CommonsBackedPool.java:137)
    at org.scale7.cassandra.pelops.pool.CommonsBackedPool.<init>(CommonsBackedPool.java:88)
    at org.scale7.cassandra.pelops.pool.CommonsBackedPool.<init>(CommonsBackedPool.java:76)
    at org.scale7.cassandra.pelops.Pelops.addPool(Pelops.java:48)
    at CSTest.main(CSTest.java:30)
# java -cp apache-cassandra-1.0.0.jar:apache-cassandra-thrift-1.0.0.jar:scale7-pelops-1.3-1.0.x-SNAPSHOT.jar:scale7-core-1.4-SNAPSHOT.jar:slf4j-simple-1.6.3.jar:slf4j-api-1.6.3.jar:commons-pool-1.5.6.jar:apache-cassandra-thrift-1.0.0.jar:libthrift-0.7.0.jar:.      CSTest

**Comment by denen99** [comment]
nevermind, i was using thrift .7 instead of .6, works now.
