### ISSUE TITLE
Why?Thanks

### ISSUE THREAD

**Issue by lixinchinaren** [s7/scale7-pelops#6]
java.lang.Exception: No Cassandra nodes are available
    at org.scale7.cassandra.pelops.CachePerNodePool.getConnectionExcept(CachePerNodePool.java:148)
    at org.scale7.cassandra.pelops.Operand.tryOperation(Operand.java:41)
    at org.scale7.cassandra.pelops.Selector.getColumnCount(Selector.java:261)
    at org.scale7.cassandra.pelops.Selector.getSuperColumnCount(Selector.java:229)

**Comment by danwashusen** [comment]
Could you give a little more context?

**Comment by lixinchinaren** [comment]
Thanks, i have ignore this problem.

**Comment by danwashusen** [comment]
Closing.
