### ISSUE TITLE
Please tell me why?Thanks!

### ISSUE THREAD

**Issue by lixinchinaren** [s7/scale7-pelops#7]
```
i want to insert an keyspace

                             Cluster clu = new Cluster("localhost", 9160);
    clu.setFramedTransportRequired(false);

    List<CfDef> list= new ArrayList<CfDef>();
    CfDef entryCf = new CfDef("LDAP", "entrySuperColumnFamily");
    entryCf.setColumn_type("Super");
    entryCf.setSubcomparator_type("BytesType");
    list.add(entryCf);

    CfDef attributeCf = new CfDef("LDAP", "attributeSuperColumnFamily");
    attributeCf.setColumn_type("Super");
    attributeCf.setSubcomparator_type("BytesType");
    list.add(attributeCf);

    CfDef indexCf = new CfDef("LDAP", "indexColumnFamily");
    list.add(indexCf);

    KsDef ks = new KsDef("LDAP", "OldNetworkTopologyStrategy", 1, list);

    try {
          Pelops.createKeyspaceManager(clu).addKeyspace(ks);
    } catch (Exception e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
```

then i get this exception

```
                           InvalidRequestException(why:OldNetworkTopologyStrategy)
at org.apache.cassandra.thrift.Cassandra$system_add_keyspace_result.read(Cassandra.java:24277)
at org.apache.cassandra.thrift.Cassandra$Client.recv_system_add_keyspace(Cassandra.java:1421)
at org.apache.cassandra.thrift.Cassandra$Client.system_add_keyspace(Cassandra.java:1396)
at org.scale7.cassandra.pelops.KeyspaceManager$4.execute(KeyspaceManager.java:63)
at org.scale7.cassandra.pelops.KeyspaceManager$4.execute(KeyspaceManager.java:1)
at org.scale7.cassandra.pelops.ManagerOperand.tryOperation(ManagerOperand.java:111)
at org.scale7.cassandra.pelops.KeyspaceManager.addKeyspace(KeyspaceManager.java:66)
at TestPelops7.main(TestPelops7.java:48)
```

**Comment by lixinchinaren** [comment]
wait for help

**Comment by danwashusen** [comment]
It would appear that the exception is telling you why it's not working: "InvalidRequestException(why:OldNetworkTopologyStrategy)"

It would be better if you raised questions like this on either the Cassandra users mailing list of the Pelops mailing list (http://groups.google.com/group/scale7) instead of creating issues...

**Comment by lixinchinaren** [comment]
thanks! by the way, would you tell me the version of Pelops to cassandra-0.6.5?
